name: pc
base: core20
version: '16.04-0.9'
type: gadget
summary: PC gadget for generic devices
description: |
    This gadget enables generic aarch64 devices to work with Ubuntu Core
grade: stable
confinement: strict
icon: icon.png

parts:
  grub-prepare:
    plugin: nil
    stage-packages:
      - grub-efi-arm64-signed
      - grub-efi-arm64-bin
    prime: [ -* ]
  grub:
    source: .
    build-packages:
      - grub-common
    plugin: make
    after: [grub-prepare]
  fwts:
    plugin: nil
    override-prime: mkdir fwts
